### scikit-learn-random forest

In [578]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.externals import joblib

Loading the dataset from url: "http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

In [479]:
dataset_url = 'http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
data = pd.read_csv(dataset_url, delimiter=';')

In [480]:
data.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [406]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

#### Splitting data into features matrix[X] and target labels[y] 

In [407]:
y = data.quality
X = data.drop('quality', axis=1)

###### Train_test_split to split the data into train set to train the model and test set to verify accuracy of the model[accuracy]

In [419]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [98]:
#mean of each feature
preprocessing.StandardScaler().fit(X_train).mean_

array([ 8.31000782,  0.5268921 ,  0.27218139,  2.54781079,  0.08751212,
       15.96833464, 46.62548866,  0.99674778,  3.3112588 ,  0.66195465,
       10.42077144])

In [99]:
#standard deviation of each feature
preprocessing.StandardScaler().fit(X_train).scale_

array([1.73288839e+00, 1.78945463e-01, 1.95711277e-01, 1.43399033e+00,
       4.82635257e-02, 1.05752254e+01, 3.26400885e+01, 1.87479464e-03,
       1.55643569e-01, 1.74554752e-01, 1.05918910e+00])

In [100]:
#variance of each feature (formula: var=sum(each val-mean of val)/total number of val)
preprocessing.StandardScaler().fit(X_train).var_

array([3.00290219e+00, 3.20214786e-02, 3.83029038e-02, 2.05632828e+00,
       2.32936791e-03, 1.11835393e+02, 1.06537538e+03, 3.51485496e-06,
       2.42249205e-02, 3.04693615e-02, 1.12188155e+00])

In [103]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)

In [460]:
joblib.dump(scaler, 'D:\\abc.pkl')

['D:\\abc.pkl']

In [461]:
pickle_scaler = joblib.load('D:\\abc.pkl')

In [465]:
pickle_scaler.mean_

array([ 8.31000782,  0.5268921 ,  0.27218139,  2.54781079,  0.08751212,
       15.96833464, 46.62548866,  0.99674778,  3.3112588 ,  0.66195465,
       10.42077144])

In [462]:
#returns total number of samples processed for each feature
#integer if no missing sample else an array
pickle_scaler.n_samples_seen_

1279

In [118]:
#mean of each column i.e. axis=0
X_train_scaled.mean(axis=0)

array([ 1.16664562e-16, -3.05550043e-17, -8.47206937e-17, -2.22218213e-17,
        2.22218213e-17, -6.38877362e-17, -4.16659149e-18, -2.54439854e-15,
       -8.70817622e-16, -4.08325966e-16, -1.17220107e-15])

In [119]:
#Standard Deviation of each column i.e. axis=0
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
X_test_scaled = scaler.transform(X_test)

In [122]:
X_test_scaled.std(axis=0)

array([1.02160495, 1.00135689, 0.97456598, 0.91099054, 0.86716698,
       0.94193125, 1.03673213, 1.03145119, 0.95734849, 0.83829505,
       1.0286218 ])

#### Pipeline creation

In [420]:
pipeline = make_pipeline(RandomForestClassifier(n_estimators=100))

In [421]:
pipeline

Pipeline(memory=None,
     steps=[('randomforestclassifier', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [422]:
pipeline.get_params()

{'memory': None,
 'randomforestclassifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False),
 'randomforestclassifier__bootstrap': True,
 'randomforestclassifier__class_weight': None,
 'randomforestclassifier__criterion': 'gini',
 'randomforestclassifier__max_depth': None,
 'randomforestclassifier__max_features': 'auto',
 'randomforestclassifier__max_leaf_nodes': None,
 'randomforestclassifier__min_impurity_decrease': 0.0,
 'randomforestclassifier__min_impurity_split': None,
 'randomforestclassifier__min_samples_leaf': 1,
 'randomforestclassifier__min_samples_split': 2,
 'randomforestclassifier__min_weight_fra

In [444]:
hyperparameters = {"randomforestclassifier__n_estimators":[100, 300, 500, 1000], "randomforestclassifier__criterion":['gini', 'entropy']}

In [431]:
est = RandomForestClassifier(n_estimators=100)

In [453]:
est.feature_importances_

array([0.0748842 , 0.10446619, 0.07418344, 0.07123481, 0.07804954,
       0.06867208, 0.10044072, 0.08719801, 0.07341408, 0.11704033,
       0.15041659])

In [432]:
est.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [506]:
data.columns[:-1]

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [496]:
est.estimators_[5]

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False,
            random_state=1277839348, splitter='best')

In [433]:
pred = est.predict(X_test)

#### Accuracy Score without tuning the parameters

In [434]:
accuracy_score(y_test, pred)

0.74375

In [308]:
confusion_matrix(y_test, pred)

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   6,   5,   0,   0],
       [  0,   0, 113,  22,   1,   0],
       [  0,   0,  30,  94,   4,   0],
       [  0,   0,   3,  19,  18,   0],
       [  0,   0,   0,   2,   1,   0]], dtype=int64)

#### Implemented GridSearchCV to tune hyperparameters

In [466]:
clf = GridSearchCV(pipeline, hyperparameters, cv=5, scoring='accuracy', iid=True)

In [467]:
clf.get_params()

{'cv': 5,
 'error_score': 'raise-deprecating',
 'estimator': Pipeline(memory=None,
      steps=[('randomforestclassifier', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False))]),
 'estimator__memory': None,
 'estimator__randomforestclassifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random

In [468]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Pipeline(memory=None,
     steps=[('randomforestclassifier', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))]),
       fit_params=None, iid=True, n_jobs=None,
       param_grid={'randomforestclassifier__n_estimators': [100, 300, 500, 1000], 'randomforestclassifier__criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [476]:
clf.best_estimator_

Pipeline(memory=None,
     steps=[('randomforestclassifier', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [469]:
clf.best_params_

{'randomforestclassifier__criterion': 'gini',
 'randomforestclassifier__n_estimators': 500}

In [470]:
clf.refit

True

In [471]:
clf.best_score_

0.6661454261141517

In [472]:
x_test_pred = clf.predict(X_test)

### with GirdSearchCV Scoring parameter[Accuracy]

In [618]:
clf.score(X_test, y_test)

0.725

### Accuracy Score after prediction

In [619]:
accuracy_score(y_test, x_test_pred)

0.725

### Confusion Matrix

In [620]:
confusion_matrix(y_test, x_test_pred)

array([[  0,   0,   0,   2,   0,   0],
       [  0,   0,   6,   5,   0,   0],
       [  0,   0, 113,  20,   2,   0],
       [  0,   0,  29, 104,   9,   0],
       [  0,   0,   1,   9,  15,   2],
       [  0,   0,   0,   1,   2,   0]], dtype=int64)